### ISSUE TITLE
Instantiate without new

### ISSUE THREAD

**Issue by iAziz786** [badrap/bar-of-progress#2]
What happens when someone forgot to call `new` while instantiating the `ProgressBar`? It seems better to instantiate and return it implicitly if users forgot to add it.

**Comment by jviide** [comment]
Thanks for creating this issue, you raise a good point. JavaScript indeed allows calling `ProgressBar` without `new`. Depending on the environment this would throw an error either when `ProgressBar` is called or when `.start()` (or `.finish()`) is first called.

As a fan of avoiding multiple ways of doing the same thing I'd like to avoid the situation where both `ProgressBar()` and `new ProgressBar()` are supported. This is just a matter of personal preference, however 🙂 One way to solve this would be to get rid of the `new` altogether and change the function to something like `createProgressBar()`.

In the end I went with the *other* option and converted the library to TypeScript (see [the diff here](https://github.com/badrap/bar-of-progress/compare/v0.1.0..v0.1.1#diff-f41e9d04a45c83f3b6f6e630f10117fe)) as TypeScript support was something we wanted to do anyway. IDEs are making strides with detecting whether a function should be called with or without a `new`, and the typings potentially help there. This way the users can get nice warnings in their editor on missing `new`, along with other useful documentation, while keeping the library itself minimal.

I hope this is ok for you 🙂 The version with the TypeScript typings has been published as v0.1.1.

**Comment by iAziz786** [comment]
As long as the API is clear, which is now by the use of new TypeScript support, it is okay. Creating libraries with explicit API is much better than implicit ones. :+1:

**Comment by jviide** [comment]
Great! I think we can close this issue then 👍
